# AlarmManager中的配置属性
# 时间
SYSTEM_TIME = 0

# type类别
RTC_WAKEUP = 0
RTC = 1
ELAPSED_REALTIME_WAKEUP = 2
ELAPSED_REALTIME = 3

# 必要的时间
INTERVAL_FIFTEEN_MINUTES = 15 * 60 * 1000
INTERVAL_HALF_HOUR = 2 * INTERVAL_FIFTEEN_MINUTES
INTERVAL_HOUR = 2 * INTERVAL_HALF_HOUR
INTERVAL_HALF_DAY = 12*INTERVAL_HOUR
INTERVAL_DAY = 2*INTERVAL_HALF_DAY

# idle
DEFAULT_MIN_DEVICE_IDLE_FUZZ = 2 * 60 * 1000
DEFAULT_MAX_DEVICE_IDLE_FUZZ = 15 * 60 * 1000

MIN_DEVICE_IDLE_FUZZ = DEFAULT_MIN_DEVICE_IDLE_FUZZ
MAX_DEVICE_IDLE_FUZZ = DEFAULT_MAX_DEVICE_IDLE_FUZZ


# alarm的最小时间间隔
MIN_INTERVAL = 60*1000

MIN_FUTURITY = 5*1000

MAX_INTERVAL = 365*INTERVAL_DAY


